apiVersion: v1
kind: Service
metadata:
  name: ece-userapi
  labels:
    app: ece-userapi
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: ece-userapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ece-userapi
  labels:
    app: ece-userapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ece-userapi
  template:
    metadata:
      labels:
        app: ece-userapi
    spec:
      containers:
      - name: ece-userapi
        image: negrillon/devopsproject:latest
        ports:
        - containerPort: 3000
